import React from 'react';
import {
  Sparkles,
  Minus,
  Maximize2,
  Layers,
  Box,
  Shapes,
  Square,
  Component,
  Tv,
  LayoutGrid,
  Palette,
  LayoutTemplate,
  Zap,
  Radio,
  Terminal,
  Newspaper,
  LucideIcon,
} from 'lucide-react';

export type ThemeId =
  | 'main'
  | 'minimalism'
  | 'maximalism'
  | 'glassmorphism'
  | 'neumorphism'
  | 'claymorphism'
  | 'brutalism'
  | 'neo-brutalism'
  | 'skeuomorphism'
  | 'flat'
  | 'material'
  | 'bento'
  | 'y2k'
  | 'retro'
  | 'cyberpunk'
  | 'editorial';

export interface ThemeDefinition {
  id: ThemeId;
  index: number;
  name: string;
  icon: LucideIcon;
  badge: string;
  bgClass: string;
  cardClass: string;
  cardHeaderBg: string;
  borderClass: string;
  textPrimary: string;
  textMuted: string;
  accentClass: string;
  buttonClass: string;
  fontClass?: string;
  hasBlobs: boolean;
  pillRadius: string;
  cardRadius: string;
}

export const THEMES: ThemeDefinition[] = [
  {
    id: 'main',
    index: 0,
    name: 'Main (Google Labs)',
    icon: Sparkles,
    badge: 'Default',
    bgClass: 'bg-[#F6F8F6]',
    cardClass: 'bg-white shadow-xs hover:shadow-md border border-gray-200/90',
    cardHeaderBg: 'bg-transparent',
    borderClass: 'border-gray-200/90',
    textPrimary: 'text-gray-900',
    textMuted: 'text-gray-500',
    accentClass: 'text-purple-600 bg-purple-50',
    buttonClass: 'bg-white hover:bg-gray-50 text-gray-800 border-gray-200/90 shadow-xs',
    hasBlobs: true,
    pillRadius: 'rounded-full',
    cardRadius: 'rounded-2xl',
  },
  {
    id: 'minimalism',
    index: 1,
    name: 'Minimalism',
    icon: Minus,
    badge: 'Clean',
    bgClass: 'bg-[#FAFAFA]',
    cardClass: 'bg-white border border-neutral-200 shadow-none hover:border-neutral-400',
    cardHeaderBg: 'bg-neutral-50/50',
    borderClass: 'border-neutral-200',
    textPrimary: 'text-neutral-900',
    textMuted: 'text-neutral-400',
    accentClass: 'text-neutral-900 bg-neutral-100',
    buttonClass: 'bg-white hover:bg-neutral-100 text-neutral-800 border-neutral-200 shadow-none',
    hasBlobs: false,
    pillRadius: 'rounded-md',
    cardRadius: 'rounded-lg',
  },
  {
    id: 'maximalism',
    index: 2,
    name: 'Maximalism',
    icon: Maximize2,
    badge: 'Vibrant',
    bgClass: 'bg-gradient-to-br from-fuchsia-100 via-rose-50 to-amber-100',
    cardClass: 'bg-white/95 shadow-xl border-2 border-fuchsia-400 hover:border-fuchsia-600',
    cardHeaderBg: 'bg-gradient-to-r from-fuchsia-50 to-amber-50',
    borderClass: 'border-fuchsia-300',
    textPrimary: 'text-gray-950 font-black',
    textMuted: 'text-fuchsia-800 font-semibold',
    accentClass: 'text-white bg-gradient-to-r from-fuchsia-600 to-amber-500 font-bold',
    buttonClass: 'bg-gradient-to-r from-fuchsia-500 to-pink-500 text-white border-fuchsia-600 shadow-md font-bold hover:brightness-105',
    hasBlobs: true,
    pillRadius: 'rounded-2xl',
    cardRadius: 'rounded-3xl',
  },
  {
    id: 'glassmorphism',
    index: 3,
    name: 'Glassmorphism',
    icon: Layers,
    badge: 'Frosted',
    bgClass: 'bg-gradient-to-br from-slate-900 via-purple-950 to-indigo-950 text-slate-100',
    cardClass: 'bg-white/10 backdrop-blur-md border border-white/20 shadow-2xl hover:bg-white/15',
    cardHeaderBg: 'bg-white/5 backdrop-blur-sm',
    borderClass: 'border-white/20',
    textPrimary: 'text-white',
    textMuted: 'text-slate-300',
    accentClass: 'text-cyan-300 bg-cyan-500/20 border border-cyan-400/30',
    buttonClass: 'bg-white/10 hover:bg-white/20 text-white border-white/20 backdrop-blur-md',
    hasBlobs: true,
    pillRadius: 'rounded-full',
    cardRadius: 'rounded-2xl',
  },
  {
    id: 'neumorphism',
    index: 4,
    name: 'Neumorphism',
    icon: Box,
    badge: 'Soft 3D',
    bgClass: 'bg-[#e0e5ec]',
    cardClass: 'bg-[#e0e5ec] shadow-[8px_8px_16px_#bec3c9,-8px_-8px_16px_#ffffff] border-none hover:shadow-[12px_12px_24px_#bec3c9,-12px_-12px_24px_#ffffff]',
    cardHeaderBg: 'bg-[#e0e5ec]',
    borderClass: 'border-transparent',
    textPrimary: 'text-[#3d4451]',
    textMuted: 'text-[#7e889b]',
    accentClass: 'text-indigo-600 bg-[#e0e5ec] shadow-[inset_2px_2px_5px_#bec3c9,inset_-2px_-2px_5px_#ffffff]',
    buttonClass: 'bg-[#e0e5ec] text-[#3d4451] shadow-[4px_4px_8px_#bec3c9,-4px_-4px_8px_#ffffff] active:shadow-[inset_2px_2px_4px_#bec3c9,inset_-2px_-2px_4px_#ffffff]',
    hasBlobs: false,
    pillRadius: 'rounded-xl',
    cardRadius: 'rounded-2xl',
  },
  {
    id: 'claymorphism',
    index: 5,
    name: 'Claymorphism',
    icon: Shapes,
    badge: 'Clay Pillows',
    bgClass: 'bg-[#f0f3fa]',
    cardClass: 'bg-[#ffffff] shadow-[8px_8px_16px_rgba(166,180,200,0.4),inset_-6px_-6px_12px_rgba(0,0,0,0.05),inset_6px_6px_12px_rgba(255,255,255,0.9)] border-2 border-white/80',
    cardHeaderBg: 'bg-[#f8faff]',
    borderClass: 'border-white',
    textPrimary: 'text-slate-800',
    textMuted: 'text-slate-500',
    accentClass: 'text-indigo-700 bg-indigo-50 shadow-[inset_2px_2px_4px_rgba(0,0,0,0.06)]',
    buttonClass: 'bg-white hover:bg-slate-50 text-slate-700 shadow-[4px_4px_8px_rgba(166,180,200,0.35),inset_-2px_-2px_4px_rgba(0,0,0,0.04),inset_2px_2px_4px_rgba(255,255,255,0.9)] border border-white',
    hasBlobs: true,
    pillRadius: 'rounded-2xl',
    cardRadius: 'rounded-3xl',
  },
  {
    id: 'brutalism',
    index: 6,
    name: 'Brutalism',
    icon: Square,
    badge: 'Raw Raw',
    bgClass: 'bg-[#FFFFFF]',
    cardClass: 'bg-white border-3 border-black shadow-[5px_5px_0px_#000000] rounded-none hover:shadow-[7px_7px_0px_#000000]',
    cardHeaderBg: 'bg-black text-white',
    borderClass: 'border-black',
    textPrimary: 'text-black font-mono',
    textMuted: 'text-black/80 font-mono',
    accentClass: 'text-black bg-yellow-300 border-2 border-black font-mono font-bold',
    buttonClass: 'bg-white hover:bg-yellow-200 text-black border-2 border-black shadow-[3px_3px_0px_#000000] font-mono font-bold rounded-none',
    hasBlobs: false,
    pillRadius: 'rounded-none',
    cardRadius: 'rounded-none',
  },
  {
    id: 'neo-brutalism',
    index: 7,
    name: 'Neo-Brutalism',
    icon: Component,
    badge: 'Modern Pop',
    bgClass: 'bg-[#FFFBEA]',
    cardClass: 'bg-white border-2 border-black shadow-[4px_4px_0px_#000000] hover:translate-x-[-1px] hover:translate-y-[-1px] hover:shadow-[6px_6px_0px_#000000] transition-all',
    cardHeaderBg: 'bg-amber-100/70 border-b-2 border-black',
    borderClass: 'border-black',
    textPrimary: 'text-gray-950 font-bold',
    textMuted: 'text-gray-700',
    accentClass: 'text-black bg-[#A3E635] border-2 border-black font-bold',
    buttonClass: 'bg-[#FED7AA] hover:bg-[#FDBA74] text-black border-2 border-black shadow-[2px_2px_0px_#000000] font-bold',
    hasBlobs: false,
    pillRadius: 'rounded-lg',
    cardRadius: 'rounded-xl',
  },
  {
    id: 'skeuomorphism',
    index: 8,
    name: 'Skeuomorphism',
    icon: Tv,
    badge: 'Classic Real',
    bgClass: 'bg-[#E5E5E5] bg-radial from-[#F5F5F5] to-[#D5D5D5]',
    cardClass: 'bg-gradient-to-b from-[#FFFFFF] to-[#EAEAEA] border border-[#BFBFBF] shadow-[inset_0_1px_0_rgba(255,255,255,0.9),0_2px_5px_rgba(0,0,0,0.2)]',
    cardHeaderBg: 'bg-gradient-to-b from-[#F9F9F9] to-[#E5E5E5] border-b border-[#D0D0D0]',
    borderClass: 'border-[#C0C0C0]',
    textPrimary: 'text-[#222222]',
    textMuted: 'text-[#666666]',
    accentClass: 'text-blue-900 bg-gradient-to-b from-[#E0F0FF] to-[#BADBFF] border border-[#85B8EB]',
    buttonClass: 'bg-gradient-to-b from-[#FFFFFF] via-[#ECECEC] to-[#D8D8D8] hover:from-[#F0F0F0] hover:to-[#CECECE] text-[#333333] border border-[#AAAAAA] shadow-[inset_0_1px_0_#FFF,0_1px_2px_rgba(0,0,0,0.15)] font-medium',
    hasBlobs: false,
    pillRadius: 'rounded-md',
    cardRadius: 'rounded-xl',
  },
  {
    id: 'flat',
    index: 9,
    name: 'Flat Design',
    icon: LayoutGrid,
    badge: '2D Crisp',
    bgClass: 'bg-[#2C3E50] text-slate-100',
    cardClass: 'bg-[#34495E] border-none shadow-none hover:bg-[#3d566e]',
    cardHeaderBg: 'bg-[#2C3E50]',
    borderClass: 'border-transparent',
    textPrimary: 'text-white',
    textMuted: 'text-slate-300',
    accentClass: 'text-white bg-[#E74C3C] font-semibold',
    buttonClass: 'bg-[#1ABC9C] hover:bg-[#16A085] text-white border-none shadow-none font-bold',
    hasBlobs: false,
    pillRadius: 'rounded-none',
    cardRadius: 'rounded-sm',
  },
  {
    id: 'material',
    index: 10,
    name: 'Material Design',
    icon: Palette,
    badge: 'M3 Elevation',
    bgClass: 'bg-[#FEF7FF]',
    cardClass: 'bg-[#F3EDF7] border border-[#CAC4D0] shadow-sm hover:shadow-md transition-shadow',
    cardHeaderBg: 'bg-[#E8DEF8]/50',
    borderClass: 'border-[#CAC4D0]',
    textPrimary: 'text-[#1D1B20]',
    textMuted: 'text-[#49454F]',
    accentClass: 'text-[#381E72] bg-[#E8DEF8] font-medium',
    buttonClass: 'bg-[#6750A4] hover:bg-[#584094] text-white border-none shadow-xs font-medium',
    hasBlobs: false,
    pillRadius: 'rounded-full',
    cardRadius: 'rounded-2xl',
  },
  {
    id: 'bento',
    index: 11,
    name: 'Bento UI',
    icon: LayoutTemplate,
    badge: 'Grid Mod',
    bgClass: 'bg-[#09090B] text-zinc-100',
    cardClass: 'bg-zinc-900/90 border border-zinc-800 shadow-xl hover:border-zinc-700 transition-colors',
    cardHeaderBg: 'bg-zinc-950/40',
    borderClass: 'border-zinc-800',
    textPrimary: 'text-zinc-100',
    textMuted: 'text-zinc-400',
    accentClass: 'text-emerald-400 bg-emerald-950/60 border border-emerald-800/60',
    buttonClass: 'bg-zinc-800 hover:bg-zinc-700 text-zinc-200 border border-zinc-700 shadow-none',
    hasBlobs: true,
    pillRadius: 'rounded-xl',
    cardRadius: 'rounded-2xl',
  },
  {
    id: 'y2k',
    index: 12,
    name: 'Y2K Design',
    icon: Zap,
    badge: 'Millennium',
    bgClass: 'bg-gradient-to-b from-[#0F0C29] via-[#302B63] to-[#24243E] text-pink-100',
    cardClass: 'bg-[#1E1B4B]/80 backdrop-blur-sm border-2 border-pink-500 shadow-[0_0_15px_rgba(236,72,153,0.4)] hover:shadow-[0_0_25px_rgba(236,72,153,0.7)]',
    cardHeaderBg: 'bg-gradient-to-r from-pink-600/40 to-cyan-500/40',
    borderClass: 'border-pink-500',
    textPrimary: 'text-white font-mono',
    textMuted: 'text-pink-200 font-mono',
    accentClass: 'text-cyan-300 bg-pink-900/60 border border-cyan-400 font-mono font-bold',
    buttonClass: 'bg-gradient-to-r from-pink-500 to-cyan-500 hover:from-pink-600 hover:to-cyan-600 text-white border border-white font-mono font-bold shadow-[0_0_10px_rgba(6,182,212,0.5)]',
    hasBlobs: true,
    pillRadius: 'rounded-full',
    cardRadius: 'rounded-2xl',
  },
  {
    id: 'retro',
    index: 13,
    name: 'Retro Design',
    icon: Radio,
    badge: '70s Warmth',
    bgClass: 'bg-[#FDF6E2] text-[#4A3728]',
    cardClass: 'bg-[#F4ECD8] border-2 border-[#D39E5E] shadow-[4px_4px_0px_#B87333] hover:shadow-[6px_6px_0px_#B87333]',
    cardHeaderBg: 'bg-[#EBDDC3] border-b-2 border-[#D39E5E]',
    borderClass: 'border-[#D39E5E]',
    textPrimary: 'text-[#4A3728] font-serif',
    textMuted: 'text-[#8A6A4B] font-serif',
    accentClass: 'text-[#FDF6E2] bg-[#C85A17] font-serif font-bold',
    buttonClass: 'bg-[#D39E5E] hover:bg-[#C85A17] text-[#FDF6E2] border-2 border-[#4A3728] shadow-[2px_2px_0px_#4A3728] font-serif font-bold',
    hasBlobs: false,
    pillRadius: 'rounded-lg',
    cardRadius: 'rounded-xl',
  },
  {
    id: 'cyberpunk',
    index: 14,
    name: 'Cyberpunk',
    icon: Terminal,
    badge: '2077 Glitch',
    bgClass: 'bg-[#050505] text-[#00FF66]',
    cardClass: 'bg-[#0d0d0d] border-2 border-[#00FF66] shadow-[0_0_10px_rgba(0,255,102,0.3)] hover:shadow-[0_0_20px_rgba(0,255,102,0.6)] hover:border-[#FCEE09]',
    cardHeaderBg: 'bg-[#1a1a1a] border-b-2 border-[#00FF66]',
    borderClass: 'border-[#00FF66]',
    textPrimary: 'text-[#00FF66] font-mono',
    textMuted: 'text-[#FCEE09] font-mono',
    accentClass: 'text-black bg-[#FCEE09] border border-black font-mono font-bold',
    buttonClass: 'bg-[#00FF66] hover:bg-[#FCEE09] text-black border-2 border-black font-mono font-black shadow-[2px_2px_0px_#FCEE09]',
    hasBlobs: true,
    pillRadius: 'rounded-none',
    cardRadius: 'rounded-none',
  },
  {
    id: 'editorial',
    index: 15,
    name: 'Editorial Design',
    icon: Newspaper,
    badge: 'Vogue Print',
    bgClass: 'bg-[#F9F7F1] text-[#111111]',
    cardClass: 'bg-white border-t-2 border-b-2 border-l-0 border-r-0 border-black shadow-none hover:bg-[#FAF9F5]',
    cardHeaderBg: 'bg-[#F5F2EA] border-b border-black',
    borderClass: 'border-black',
    textPrimary: 'text-[#111111] font-serif tracking-tight',
    textMuted: 'text-[#555555] font-serif italic',
    accentClass: 'text-white bg-black font-serif uppercase tracking-widest',
    buttonClass: 'bg-black hover:bg-neutral-800 text-white border-none font-serif tracking-wider shadow-none',
    hasBlobs: false,
    pillRadius: 'rounded-none',
    cardRadius: 'rounded-none',
  },
];
